### ISSUE TITLE
Issue with receiving data

### ISSUE THREAD

**Issue by pasuder** [project-capo/amber-python-drivers#39]
```
2015-11-28 15:29:27,647 - AmberPipes - CRITICAL - Stop due to error on pipe with mediator
Traceback (most recent call last):
  File "/home/panda/amber/amber-python-drivers/src/amberdriver/common/amber_pipes.py", line 54, in __amber_pipes_loop
    header, message = self.__read_header_and_message_from_pipe()
  File "/home/panda/amber/amber-python-drivers/src/amberdriver/common/amber_pipes.py", line 71, in __read_header_and_message_from_pipe
    header = self.__read_data_from_pipe(header)
  File "/home/panda/amber/amber-python-drivers/src/amberdriver/common/amber_pipes.py", line 77, in __read_data_from_pipe
    data = self.__read_and_unpack_data_from_pipe(LEN_SIZE)
  File "/home/panda/amber/amber-python-drivers/src/amberdriver/common/amber_pipes.py", line 90, in __read_and_unpack_data_from_pipe
    size = struct.unpack('!h', data)
error: unpack requires a string argument of length 2
```

**Comment by pasuder** [comment]
Packet capture [`output.pcap`](https://github.com/project-capo/amber-python-drivers/files/46360/output.pcap.txt) (change `pcap.txt` to `pcap`).

**Comment by pasuder** [comment]
Caused by changes done in commit https://github.com/project-capo/amber-erlang-mediator/commit/fe62843b665f5d2c94b1571c38c7b37e88865225

Fixed by changes done in commit https://github.com/project-capo/amber-erlang-mediator/commit/8b4438f2fc2f738d74f13fb6d5ec67c6de677aea
